[theme]
base = "light"
primaryColor = "#762f35"
backgroundColor = "#f3efe6"
secondaryBackgroundColor = "#eae4d9"
textColor = "#1d1d1a"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
