[theme]
base = "light"
primaryColor = "#c62717"
backgroundColor = "#f8f8f4"
secondaryBackgroundColor = "#efeee8"
textColor = "#171713"
font = "monospace"

[browser]
gatherUsageStats = false

[server]
headless = true
